# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 431, 521))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.contenitore_lancette = QtWidgets.QGraphicsView(self.page)
        self.contenitore_lancette.setGeometry(QtCore.QRect(0, 0, 431, 491))
        self.contenitore_lancette.setObjectName("contenitore_lancette")
        self.velocita_text = QtWidgets.QLabel(self.page)
        self.velocita_text.setGeometry(QtCore.QRect(280, 58, 120, 16))
        self.velocita_text.setObjectName("velocita_text")
        self.girimotore_text = QtWidgets.QLabel(self.page)
        self.girimotore_text.setGeometry(QtCore.QRect(280, 176, 120, 16))
        self.girimotore_text.setObjectName("girimotore_text")
        self.pedaleacc_text = QtWidgets.QLabel(self.page)
        self.pedaleacc_text.setGeometry(QtCore.QRect(280, 292, 120, 16))
        self.pedaleacc_text.setObjectName("pedaleacc_text")
        self.temperatura_text = QtWidgets.QLabel(self.page)
        self.temperatura_text.setGeometry(QtCore.QRect(280, 410, 120, 16))
        self.temperatura_text.setObjectName("temperatura_text")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(80, 70, 49, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(360, 500, 80, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 503, 80, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.velocita_text.setText(_translate("MainWindow", "TextLabel"))
        self.girimotore_text.setText(_translate("MainWindow", "TextLabel"))
        self.pedaleacc_text.setText(_translate("MainWindow", "TextLabel"))
        self.temperatura_text.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "pagina 2"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
