# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.velocita_text = QtWidgets.QLabel(self.centralwidget)
        self.velocita_text.setGeometry(QtCore.QRect(300, 90, 250, 16))
        self.velocita_text.setObjectName("velocita_text")
        self.girimotore_text = QtWidgets.QLabel(self.centralwidget)
        self.girimotore_text.setGeometry(QtCore.QRect(300, 230, 250, 16))
        self.girimotore_text.setObjectName("girimotore_text")
        self.temperatura_text = QtWidgets.QLabel(self.centralwidget)
        self.temperatura_text.setGeometry(QtCore.QRect(300, 510, 250, 16))
        self.temperatura_text.setObjectName("temperatura_text")
        self.pedaleacc_text = QtWidgets.QLabel(self.centralwidget)
        self.pedaleacc_text.setGeometry(QtCore.QRect(300, 370, 250, 16))
        self.pedaleacc_text.setObjectName("pedaleacc_text")
        self.contenitore_lancette = QtWidgets.QGraphicsView(self.centralwidget)
        self.contenitore_lancette.setGeometry(QtCore.QRect(20, 19, 251, 541))
        self.contenitore_lancette.setObjectName("contenitore_lancette")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.velocita_text.setText(_translate("MainWindow", "TextLabel"))
        self.girimotore_text.setText(_translate("MainWindow", "TextLabel"))
        self.temperatura_text.setText(_translate("MainWindow", "TextLabel"))
        self.pedaleacc_text.setText(_translate("MainWindow", "TextLabel"))
