# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 431, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.contenitore_lancette = QtWidgets.QGraphicsView(self.page)
        self.contenitore_lancette.setGeometry(QtCore.QRect(0, 0, 431, 461))
        self.contenitore_lancette.setObjectName("contenitore_lancette")
        self.velocita_text = QtWidgets.QLabel(self.page)
        self.velocita_text.setGeometry(QtCore.QRect(280, 58, 120, 16))
        self.velocita_text.setObjectName("velocita_text")
        self.girimotore_text = QtWidgets.QLabel(self.page)
        self.girimotore_text.setGeometry(QtCore.QRect(280, 176, 120, 16))
        self.girimotore_text.setObjectName("girimotore_text")
        self.pedaleacc_text = QtWidgets.QLabel(self.page)
        self.pedaleacc_text.setGeometry(QtCore.QRect(280, 292, 120, 16))
        self.pedaleacc_text.setObjectName("pedaleacc_text")
        self.temperatura_text = QtWidgets.QLabel(self.page)
        self.temperatura_text.setGeometry(QtCore.QRect(280, 410, 120, 16))
        self.temperatura_text.setObjectName("temperatura_text")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.contenitore_page_2 = QtWidgets.QGraphicsView(self.page_2)
        self.contenitore_page_2.setGeometry(QtCore.QRect(0, 20, 300, 300))
        self.contenitore_page_2.setObjectName("contenitore_page_2")
        self.pedaleacc_bar = QtWidgets.QProgressBar(self.page_2)
        self.pedaleacc_bar.setGeometry(QtCore.QRect(320, 20, 30, 300))
        self.pedaleacc_bar.setProperty("value", 24)
        self.pedaleacc_bar.setTextVisible(False)
        self.pedaleacc_bar.setObjectName("pedaleacc_bar")
        self.velocita_text_2 = QtWidgets.QLabel(self.page_2)
        self.velocita_text_2.setGeometry(QtCore.QRect(190, 330, 91, 91))
        font = QtGui.QFont()
        font.setFamily("Digital Display")
        font.setPointSize(50)
        self.velocita_text_2.setFont(font)
        self.velocita_text_2.setObjectName("velocita_text_2")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(360, 480, 80, 71))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.velocita_text.setText(_translate("MainWindow", "TextLabel"))
        self.girimotore_text.setText(_translate("MainWindow", "TextLabel"))
        self.pedaleacc_text.setText(_translate("MainWindow", "TextLabel"))
        self.temperatura_text.setText(_translate("MainWindow", "TextLabel"))
        self.velocita_text_2.setText(_translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
